const f=()=>{


try {
    let a=0
    console.log("Program chalra haibhai")
    // t
    return
} catch (error) {
    console.log("Kuch to gadbad hai daya:"+error)
    console.log(p)
}
finally{
    console.log("Finally Block hu beta hamesa chalunga:even if there is error in catch block also if the function returns from try")
}
}
f()
console.log("End")
